#!/usr/bin/env bash

unset IN_NIX_SHELL

nixpkgs=$(nix eval --raw '(import ./nix/sources.nix).nixpkgs')

export NIX_PATH=nixpkgs=$nixpkgs:nixos-config=/etc/nixos/configuration.nix

nix build -f $nixpkgs/nixos system $@ && {
    dir=$(pwd)
    pkexec nix-env --profile /nix/var/nix/profiles/system --set $(readlink $dir/result) &&
    pkexec $dir/result/bin/switch-to-configuration switch
}
