# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "nvme"
    "usb_storage"
    "dw_mmc_starfive"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/44444444-4444-4444-8888-888888888888";
    fsType = "ext4";
  };

  fileSystems."/tmp" = {
    device = "/dev/disk/by-uuid/8d9d0db7-601d-4b35-821a-c9281a1e1e8e";
    fsType = "btrfs";
    options = [ "subvol=tmp" ];
  };

  # fileSystems."/nix/store" =
  #  { device = "/dev/disk/by-uuid/8d9d0db7-601d-4b35-821a-c9281a1e1e8e";
  #    fsType = "btrfs";
  #    options = [ "subvol=store" ];
  #  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/1650f0bc-50cf-4631-9783-c59bc21febd6";
    fsType = "ext4";
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/733d41ec-90c8-4aa5-b92a-ef16c1b9efa8"; }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
  # networking.interfaces.ip6tnl0.useDHCP = lib.mkDefault true;
  # networking.interfaces.sit0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0u1u1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "riscv64-linux";
}
